api_version = "2026-01"
uid = "17f775b7-9c10-1172-43a0-64203ca774e5ac5a3b31"

[[extensions]]
name = "RankPilot GEO Optimize"
handle = "rankpilot-action-extension"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/ActionExtension.tsx"
target = "admin.product-details.action.render"
